apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: approved-apps-config
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/TheMagicalWizardd/demo-app-openshift.git
    targetRevision: main
    path: gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: portal-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
