apiVersion: v1
kind: ConfigMap
metadata:
  name: approved-apps
  namespace: portal-infra
data:
  apps.json: "{\n  \"demo-webapp\": {\n    \"image\": \"image-registry.openshift-image-registry.svc:5000/app-dev/demo-webapp:v1\"\
    ,\n    \"description\": \"Demo webapp voor studenten\",\n    \"port\": 8080,\n\
    \    \"version\": \"v1\"\n  }\n}\n"
