apiVersion: v1
kind: ConfigMap
metadata:
  name: approved-apps
  namespace: portal-infra
data:
  apps.json: |
    {
      "demo-webapp": {
        "image": "image-registry.openshift-image-registry.svc:5000/app-dev/demo-webapp:v5",
        "description": "Demo webapp voor studenten",
        "port": 8080,
        "version": "v5"
      },
      "demo-api": {
        "image": "image-registry.openshift-image-registry.svc:5000/app-dev/demo-api:v1",
        "description": "Demo API voor studenten",
        "port": 8080,
        "version": "v1"
      },
      "demo-dashboard": {
        "image": "image-registry.openshift-image-registry.svc:5000/app-dev/demo-dashboard:v1",
        "description": "Demo dashboard voor studenten",
        "port": 8080,
        "version": "v1"
      }
    }
